// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMdzee2QkcQ3oPyytmd3QxRm0FGM2koo',
    appId: '1:175702299790:web:a194537f2ddd9c5f80e5df',
    messagingSenderId: '175702299790',
    projectId: 'plusfitness',
    authDomain: 'plusfitness.firebaseapp.com',
    storageBucket: 'plusfitness.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11X7fLNcUxixLXzhiIdRhf0liYnBproo',
    appId: '1:175702299790:android:1154fc62790774d280e5df',
    messagingSenderId: '175702299790',
    projectId: 'plusfitness',
    storageBucket: 'plusfitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwV3RvYi60tZrcUvDu22zdGkdaYtNEASk',
    appId: '1:175702299790:ios:f07a70154c0f2c0d80e5df',
    messagingSenderId: '175702299790',
    projectId: 'plusfitness',
    storageBucket: 'plusfitness.appspot.com',
    androidClientId: '175702299790-q5e8uc08sf3i6fb5i58ikfd5u6pk27vh.apps.googleusercontent.com',
    iosClientId: '175702299790-dd6q4ig9sd4mquui8dpiihl4d43l9k1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.plusfitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwV3RvYi60tZrcUvDu22zdGkdaYtNEASk',
    appId: '1:175702299790:ios:87d0bf064c25c15f80e5df',
    messagingSenderId: '175702299790',
    projectId: 'plusfitness',
    storageBucket: 'plusfitness.appspot.com',
    androidClientId: '175702299790-q5e8uc08sf3i6fb5i58ikfd5u6pk27vh.apps.googleusercontent.com',
    iosClientId: '175702299790-cv3mhams9qtqmf8eflbj2q6p1299gcri.apps.googleusercontent.com',
    iosBundleId: 'com.example.plusfitness.RunnerTests',
  );
}
